site_name: 'python-app-10'
site_description: 'Main documentation for the python-app-10'
repo_url: https://github.com/Portfolio-jaime/python-app-10
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Overview:
      - Introducción y API: 'docs/index.md'
      - Arquitectura: 'docs/arquitectura.md'
      - CI/CD y GitOps: 'docs/cicd.md'
      - Casos de Uso y Pruebas: 'docs/uso.md'